import { VerticalTimeline } from 'react-vertical-timeline-component';
import Head from 'next/head'

import BackgroundParticles from '../components/backgroundParticles/backgroundParticles'
import Navbar from '../components/navbar/navbar'
import Banner from '../components/banner/banner'
import TypeWriter from '../components/typeWriter/typeWriter'
import Subtitle from '../components/subtitle/subtitile'
import AnimatedCard, { CardHolder } from '../components/card/class_card'
import TimeLineElement from '../components/timeLine/timeLine'

import 'bootstrap/dist/css/bootstrap.min.css';//bootstrap
import 'react-vertical-timeline-component/style.min.css';//vertical timeline
import styling from '../styles/Home.module.scss'

import projectData from '../content/project-animated-cards.json'
import workExperience from '../content/work-time-line.json'
import { classesUnpacker } from '../content/helper' 
import { Container } from 'react-bootstrap';

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ zIndex: 10 }}>
        <Navbar className={styling["show-z"]}></Navbar>
        <div id='home' className={`${styling['banner-group']} ${styling['show-z']}`}>
          <Banner/>
          <TypeWriter />
        </div>
        <Container className={styling['content-wrapper']}>
          <Subtitle hrefID='work' text='Work Experience' />
          <VerticalTimeline>
            {workExperience.data.map((rawItem, index) => {
              const item = classesUnpacker(rawItem,workExperience.classes)
              return (<TimeLineElement
                key={index}
                background={item.background}
                colour={item.colour}
                date={item.date}
                title={item.title}
                subtitle={item.subtitle}
                description={item.description}
                icon={item.icon}
                highlight={item.highlight}
              />)
            })}
          </VerticalTimeline>
            <div className={styling.break}/>
          <Subtitle hrefID='projects' text='Projects' />
          <CardHolder>
            {projectData.data.map((item, index) => {
              return (<AnimatedCard
                key={index}
                name={item.name}
                title={item.title}
                description={item.description}
                link={item.link}
                icon={item.icon}
                git={item.git}
              ></AnimatedCard>)
            })}
          </CardHolder>

        </Container>
      </div>
      <BackgroundParticles></BackgroundParticles>
    </>)
}
